spring.application.name=logistica-api
server.port=8000

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username =root
spring.datasource.password=Charlie162023
spring.datasource.url=jdbc:mysql://localhost:3306/db_logisticab2b
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sqspring.jpa.propeties.hibernate.format_sql=true
spring.jpa.properties.hibernate.format_sql=true

api.security.token.secret=${JWT_SECRET:suXd42tATzbN/ewjV6NVY0Ug2edcOGSpLYctfxS7tLE=}

#define host
spring.mail.host=smtp.gmail.com
#define a port para usar o envio de emails
spring.mail.port=587
#define usuario para autenticar com o servidor de e-mail
spring.mail.username=entreexpress032@gmail.com
#define senha para autenticar com o servidor de e-mail
spring.mail.password=fmobspduqkdjysaq 
#protcolo de transporte usado para o envio (SMTP)
spring.mail.properties.mail.transport.protocol=smtp
spring.mail.properties.mail.smtp.auth=true 
#indica se a conexao SMTP deve usar o protocolo TLS
spring.mail.properties.mail.smtp.starttls.enable=true
#indica se a conexao SMTP requere o protocolo TLS
spring.mail.properties.mail.smtp.starttls.required=true
#define a codificacao de caracteres usada para o texto do email
spring.mail.default-encoding=UTF-8
#indica se e preciso de uma conexao de teste 
#com o servidor de email deve ser feita durante a inicializacao do aplicativo.
spring.mail.test-connection=false
#define o nome do remetente usado para emails enviados
mail.from.name=EntrexEpress






