spring.application.name=logistica-api


spring.datasource.drive-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username =root
spring.datasource.password=senha 
spring.datasource.url=jdbc:mysql://localhost:3307/db_logisticab2b

spring.jpa.show-sql=true
spring.jpa.propeties.hibernate.format_sql=true

